---
title: "Dashboard pluviométrique"
execute: 
  echo: false
format:
  dashboard:
    theme: cosmo
    orientation: rows
    include-after-body: fonctions_js.html
    embed-resources: true
---

```{r setup}
library(dplyr)
library(tidyr)
library(ggplot2)
library(crosstalk)
library(plotly)
library(htmltools)

pluie <- read.csv("pluie.csv",sep=";", header=TRUE)

pluie <- pluie %>%
  gather("mois", "mm", 2:13)

pluie$mm <- as.numeric(pluie$mm)
pluie$annee <- as.factor(pluie$annee)
pluie$mois <- factor(pluie$mois, levels = c("janvier", "fevrier", "mars",
                                            "avril", "mai", "juin", "juillet",
                                            "aout", "septembre", "octobre", 
                                            "novembre", "decembre"))
```

# Accueil {.tabset}

Bienvenue sur le tableau de bord pluviométrique de Daniel.


# Visualisation annuelle {.tabset}

```{r}
shared_pluie <- highlight_key(pluie)

# shared_pluie <- SharedData$new(pluie)

filtre_annee <- filter_select(
  id = "filtre_annee",
  label = "Année",
  sharedData = shared_pluie,
  group = ~annee,
  multiple = FALSE
)


p <- plot_ly(
  data = shared_pluie,
  x = ~mois,
  y = ~mm,
  type = "bar",
  marker = list(color = ~mm)
)


bscols(
  widths = c(2, 9),
  filtre_annee,
  p
  
)
```



# Synthèse annuelle {.tabset}


```{r}
gg_annee <- ggplot(pluie) +
  aes(x = mois, y = mm, fill=mm, 
      text= paste0(mois, " ", annee, "<br>",mm," mm")) +
  scale_fill_gradient(high = "#132B43", low = "#56B1F7")+
  geom_col() +
  # scale_y_continuous(breaks=seq(0,220,25), limits = c(0,225)) +
  labs(x="", y="") +
  facet_wrap(~annee) +
  theme_bw() + 
  theme(legend.position='none',
        axis.text.x = element_text(angle = 40, hjust=1, size = 8))

plotly::ggplotly(gg_annee, tooltip = "text")
```


# Synthèse mensuelle {.tabset}

```{r}
shared_pluie2 <- highlight_key(pluie)

filtre_mois <- filter_select(id = "filtre_mois", label = "Mois", 
                  sharedData = shared_pluie2, 
                  group = ~mois, 
                  multiple = FALSE)


p2 <- plot_ly(
  data = shared_pluie2,
  x = ~annee,
  y = ~mm,
  type = "bar",
  marker = list(color = ~mm)
)

bscols(
  widths = c(2, 9),
  filtre_mois,
  p2
  
)
```


# Épisodes remarquables {.tabset}

